CREATE TYPE "RideStatus" AS ENUM ('REQUESTED', 'ACCEPTED');

ALTER TABLE "Ride"
ADD COLUMN "driverId" INTEGER,
ADD COLUMN "status" "RideStatus" NOT NULL DEFAULT 'REQUESTED';

ALTER TABLE "Ride" ADD CONSTRAINT "Ride_driverId_fkey"
FOREIGN KEY ("driverId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
